name: "PR Summary Generator"
description: "Generates a summary for Pull Requests based on commit messages"

inputs:
  groq_api_key:
    description: "API key for Groq"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4 # Checks out your repository code
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - run: pip install -r ./.github/pr-writer/requirements.txt
      shell: bash
    - run: ls -la ./.github/pr-writer/
      shell: bash
    - run: python ./.github/pr-writer/pr-writer.py
      shell: bash
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
