name: PR Summary

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write
  contents: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PR Summary
        uses: ./.github/pr-summary
        with:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
