name: "TODO Issue Creator Workflow"
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  create_todo_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Run TODO Issue Creator action
        uses: ./.github/todo-issue-creator
        with:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
